# DS 3000 - Assignment 3

**Student Name**: Julia Knopp

**Date**: 9/21/23


### Submission Instructions
Submit this `ipynb` file to canvas.

The `ipynb` format stores outputs from the last time you ran the notebook.  (When you open a notebook it has the figures and outputs of the last time you ran it too).  To ensure that your submitted `ipynb` file represents your latest code, make sure to give a fresh run `Kernel > Restart & Run All` just before uploading the `ipynb` file to Canvas.

### Academic Integrity

**Writing your homework is an individual effort.**  You may discuss general python problems with other students but under no circumstances should you observe another student's code which was written for this assignment, from this year or past years.  Pop into office hours or DM us in MS Teams if you have a specific question about your work or if you would like another pair of eyes or talk through your code.

Don't forget to cite websites which helped you solve a problem in a unique way.  You can do this in markdown near the code or with a simple one-line comment. You do not need to cite the official python documentation.

**Documentation / style counts for credit**  Please refer to the Pep-8 style, to improve the readability and consistency of your Python code. For more information, read the following article [How to Write Beautiful Python Code With PEP 8](https://realpython.com/python-pep8/) or ask your TA's for tips.

**NOTE:<span style='color:red'> Write python expressions to answer ALL questions below and ensure that you use the `print()` function to display the output.</span>** Each question should be answered in a new code cell. For example, your solution for question 1.1 should be in a different code cell from your solution for question 1.2.

## Question 1: 

The data that you are working with contains the exam grades and the overall grade for students who took a statistics course at a university. Write python code to answer the questions below and ensure that you round all numeric calculations to 2 decimal places. 

(2pts) Load the attached data into a numpy array: exam_grades.csv

(1pt) How many observations and columns are in the data set?

(2pts) What is the minimum and maximum overall course grade for the statistics course (i.e. for the entire data set).

(5pts) What time period (e.g. years) does the data set cover? Note: only display unique years (do not display duplicates).

(10 pts) For each year that you identified above, count the number of students who took the course each year.

(20 pts) For each year that you identified above, calculate the minimum, maximum, mean and standard deviation for each of the three exam scores. Summarize your findings.


In [111]:
#import numpy
import numpy as np

In [112]:
#loading in the csv file
file_name = 'exam_grades.csv'
data = np.loadtxt(file_name, delimiter=',', skiprows=1)
print(data)

[[2000.       84.5      69.5      86.5      76.2564]
 [2000.       80.       74.       67.       75.3882]
 [2000.       56.       70.       71.5      67.0564]
 ...
 [2003.       97.1429   53.5      67.2222   72.1189]
 [2003.       85.       63.       75.       67.1996]
 [2003.       72.8571   48.5      90.5556   66.4035]]


In [113]:
# How many observations and columns are in the data set?

# create the shape of the array
num_rows, num_columns = data.shape
# print statements that reveal the number of rows recorded and the number of columns
print(f'The number of observations in the dataset is: {num_rows}')
print(f'The number of columns in the dataset is: {num_columns}')

The number of observations in the dataset is: 233
The number of columns in the dataset is: 5


In [114]:
# What is the minimum and maximum overall course grade for the statistics course

# retrive the minimum grade from the 'course_grade' column
min_grade = data[:,4].min()
# round the answer to two decimal places
rounded_min_grade = round(min_grade, 2)
# print a statement that summarizes findings
print(f'The minimum overall course grade for the statistics course was', rounded_min_grade)

# retrive the maximum grade from the 'course_grade' column
max_grade = data[:,4].max()
# round the answer to two decimal places
rounded_max_grade = round(max_grade, 2)
# print a statement that summarizes findings
print(f'The maximum overall course grade for the statistics course was', rounded_max_grade)

The minimum overall course grade for the statistics course was 43.27
The maximum overall course grade for the statistics course was 97.57


In [115]:
# What time period does the data set cover? Note: only display unique years.

# retrive the data from the 'years' column
years = data[:,0]
# use the 'set' function to remove duplicate values
unique_years = (set(years))
# print an array containing a list of the possible years
print(unique_years)

{2000.0, 2001.0, 2002.0, 2003.0}


In [116]:
# For each year that you identified above, count the number of students who took the course each year.

# retrive the entire years column to analyze
years = data[:,0]
# create a list of the years to preform the 'count' operation
years_list = list(years)
# find how many times the year 2000 was listed as an input to find the number of students who took the course
count2000 = years_list.count(2000)
print(f'The number of students that took the course in 2000 was', count2000)
# find how many times the year 2001 was listed as an input to find the number of students who took the course
count2001 = years_list.count(2001)
print(f'The number of students that took the course in 2001 was', count2001)
# find how many times the year 2002 was listed as an input to find the number of students who took the course
count2002 = years_list.count(2002)
print(f'The number of students that took the course in 2002 was', count2002)
# find how many times the year 2003 was listed as an input to find the number of students who took the course
count2003 = years_list.count(2003)
print(f'The number of students that took the course in 2003 was', count2003)

TypeError: 'list' object is not callable

In [117]:
# For each year that you identified above, 
# calculate the minimum, maximum, mean and standard deviation for each of the three exam scores. 
# Summarize your findings.

# look at data where the year is 2000
y2k = data[data[:,0] == 2000]
# find the minimum, maximum, mean and standard deviation for exam 1
y2k_exam1 = y2k[:,1]
y2k_exam1_min = round(y2k_exam1.min(), 2)
y2k_exam1_max = round(y2k_exam1.max(), 2)
y2k_exam1_mean = round(y2k_exam1.mean(), 2)
y2k_exam1_sd = round(y2k_exam1.std(), 2)
# find the minimum, maximum, mean and standard deviation for exam 2
y2k_exam2 = y2k[:,2]
y2k_exam2_min = round(y2k_exam2.min(), 2)
y2k_exam2_max = round(y2k_exam2.max(), 2)
y2k_exam2_mean = round(y2k_exam2.mean(), 2)
y2k_exam2_sd = round(y2k_exam2.std(), 2)
# find the minimum, maximum, mean and standard deviation for exam 3
y2k_exam3 = y2k[:,3]
y2k_exam3_min = round(y2k_exam3.min(), 2)
y2k_exam3_max = round(y2k_exam3.max(), 2)
y2k_exam3_mean = round(y2k_exam3.mean(), 2)
y2k_exam3_sd = round(y2k_exam3.std(), 2)
# print the findings for 2000
print(f'Statistics for 2000\n'
      'Exam 1\n'
      'The minimum score was:', y2k_exam1_min, 
      '\nThe maximum score was', y2k_exam1_max, 
      '\nThe mean was', y2k_exam1_mean,
      '\nThe standard deviation was', y2k_exam1_sd,
      '\nExam 2\n'
      'The minimum score was:', y2k_exam2_min, 
      '\nThe maximum score was', y2k_exam2_max, 
      '\nThe mean was', y2k_exam2_mean,
      '\nThe standard deviation was', y2k_exam2_sd,
      '\nExam 3\n'
      'The minimum score was:', y2k_exam3_min, 
      '\nThe maximum score was', y2k_exam3_max, 
      '\nThe mean was', y2k_exam3_mean,
      '\nThe standard deviation was', y2k_exam3_sd)

# for the year 2001
y2k1 = data[data[:,0] == 2001]
# find the minimum, maximum, mean and standard deviation for exam 1
y2k1_exam1 = y2k1[:,1]
y2k1_exam1_min = round(y2k1_exam1.min(), 2)
y2k1_exam1_max = round(y2k1_exam1.max(), 2)
y2k1_exam1_mean = round(y2k1_exam1.mean(), 2)
y2k1_exam1_sd = round(y2k1_exam1.std(), 2)
# find the minimum, maximum, mean and standard deviation for exam 2
y2k1_exam2 = y2k1[:,2]
y2k1_exam2_min = round(y2k1_exam2.min(), 2)
y2k1_exam2_max = round(y2k1_exam2.max(), 2)
y2k1_exam2_mean = round(y2k1_exam2.mean(), 2)
y2k1_exam2_sd = round(y2k1_exam2.std(), 2)
# find the minimum, maximum, mean and standard deviation for exam 3
y2k1_exam3 = y2k1[:,3]
y2k1_exam3_min = round(y2k1_exam3.min(), 2)
y2k1_exam3_max = round(y2k1_exam3.max(), 2)
y2k1_exam3_mean = round(y2k1_exam3.mean(), 2)
y2k1_exam3_sd = round(y2k1_exam3.std(), 2)
# print the findings for 2001
print(f'\n\nStatistics for 2001\n'
      'Exam 1\n'
      'The minimum score was:', y2k1_exam1_min, 
      '\nThe maximum score was', y2k1_exam1_max, 
      '\nThe mean was', y2k1_exam1_mean,
      '\nThe standard deviation was', y2k1_exam1_sd,
      '\nExam 2\n'
      'The minimum score was:', y2k1_exam2_min, 
      '\nThe maximum score was', y2k1_exam2_max, 
      '\nThe mean was', y2k1_exam2_mean,
      '\nThe standard deviation was', y2k1_exam2_sd,
      '\nExam 3\n'
      'The minimum score was:', y2k1_exam3_min, 
      '\nThe maximum score was', y2k1_exam3_max, 
      '\nThe mean was', y2k1_exam3_mean,
      '\nThe standard deviation was', y2k1_exam3_sd)

# for the year 2002
y2k2 = data[data[:,0] == 2002]
# find the minimum, maximum, mean and standard deviation for exam 1
y2k2_exam1 = y2k2[:,1]
y2k2_exam1_min = round(y2k2_exam1.min(), 2)
y2k2_exam1_max = round(y2k2_exam1.max(), 2)
y2k2_exam1_mean = round(y2k2_exam1.mean(), 2)
y2k2_exam1_sd = round(y2k2_exam1.std(), 2)
# find the minimum, maximum, mean and standard deviation for exam 2
y2k2_exam2 = y2k2[:,2]
y2k2_exam2_min = round(y2k2_exam2.min(), 2)
y2k2_exam2_max = round(y2k2_exam2.max(), 2)
y2k2_exam2_mean = round(y2k2_exam2.mean(), 2)
y2k2_exam2_sd = round(y2k2_exam2.std(), 2)
# find the minimum, maximum, mean and standard deviation for exam 3
y2k2_exam3 = y2k2[:,3]
y2k2_exam3_min = round(y2k2_exam3.min(), 2)
y2k2_exam3_max = round(y2k2_exam3.max(), 2)
y2k2_exam3_mean = round(y2k2_exam3.mean(), 2)
y2k2_exam3_sd = round(y2k2_exam3.std(), 2)
# print the findings for 2002
print(f'\n\nStatistics for 2002\n'
      'Exam 1\n'
      'The minimum score was:', y2k2_exam1_min, 
      '\nThe maximum score was', y2k2_exam1_max, 
      '\nThe mean was', y2k2_exam1_mean,
      '\nThe standard deviation was', y2k2_exam1_sd,
      '\nExam 2\n'
      'The minimum score was:', y2k2_exam2_min, 
      '\nThe maximum score was', y2k2_exam2_max, 
      '\nThe mean was', y2k2_exam2_mean,
      '\nThe standard deviation was', y2k2_exam2_sd,
      '\nExam 3\n'
      'The minimum score was:', y2k2_exam3_min, 
      '\nThe maximum score was', y2k2_exam3_max, 
      '\nThe mean was', y2k2_exam3_mean,
      '\nThe standard deviation was', y2k2_exam3_sd)

# for the year 2003
y2k3 = data[data[:,0] == 2003]
# find the minimum, maximum, mean and standard deviation for exam 1
y2k3_exam1 = y2k3[:,1]
y2k3_exam1_min = round(y2k3_exam1.min(), 2)
y2k3_exam1_max = round(y2k3_exam1.max(), 2)
y2k3_exam1_mean = round(y2k3_exam1.mean(), 2)
y2k3_exam1_sd = round(y2k3_exam1.std(), 2)
# find the minimum, maximum, mean and standard deviation for exam 2
y2k3_exam2 = y2k3[:,2]
y2k3_exam2_min = round(y2k3_exam2.min(), 2)
y2k3_exam2_max = round(y2k3_exam2.max(), 2)
y2k3_exam2_mean = round(y2k3_exam2.mean(), 2)
y2k3_exam2_sd = round(y2k3_exam2.std(), 2)
# find the minimum, maximum, mean and standard deviation for exam 3
y2k3_exam3 = y2k3[:,3]
y2k3_exam3_min = round(y2k3_exam3.min(), 2)
y2k3_exam3_max = round(y2k3_exam3.max(), 2)
y2k3_exam3_mean = round(y2k3_exam3.mean(), 2)
y2k3_exam3_sd = round(y2k3_exam3.std(), 2)
# print the findings for 2003
print(f'\n\nStatistics for 2003\n'
      'Exam 1\n'
      'The minimum score was:', y2k3_exam1_min, 
      '\nThe maximum score was', y2k3_exam1_max, 
      '\nThe mean was', y2k3_exam1_mean,
      '\nThe standard deviation was', y2k3_exam1_sd,
      '\nExam 2\n'
      'The minimum score was:', y2k3_exam2_min, 
      '\nThe maximum score was', y2k3_exam2_max, 
      '\nThe mean was', y2k3_exam2_mean,
      '\nThe standard deviation was', y2k3_exam2_sd,
      '\nExam 3\n'
      'The minimum score was:', y2k3_exam3_min, 
      '\nThe maximum score was', y2k3_exam3_max, 
      '\nThe mean was', y2k3_exam3_mean,
      '\nThe standard deviation was', y2k3_exam3_sd)

# overall analysis of the data
print('\n\nAnalysis:\n'
     'Based on the findings, by breaking the data down year by year, we can see...\n'
     'for 2000, the scores stayed fairly consistent between all three exams\n'
     'for 2001, the score for exam 1 was better than the prior year, for exams 2 and 3 the grades dropped back\n'
     'for 2002, scores for all exams overall improved and the standard deviations were lower than prior years\n'
     'in 2003, scores between exams varied and standard deviations were high, indicating scores for an exam were scattered')

Statistics for 2000
Exam 1
The minimum score was: 46.5 
The maximum score was 96.0 
The mean was 74.49 
The standard deviation was 11.39 
Exam 2
The minimum score was: 41.0 
The maximum score was 99.5 
The mean was 74.19 
The standard deviation was 13.02 
Exam 3
The minimum score was: 28.0 
The maximum score was 97.0 
The mean was 73.23 
The standard deviation was 15.7


Statistics for 2001
Exam 1
The minimum score was: 58.0 
The maximum score was 98.0 
The mean was 85.01 
The standard deviation was 8.37 
Exam 2
The minimum score was: 41.5 
The maximum score was 96.5 
The mean was 71.36 
The standard deviation was 13.27 
Exam 3
The minimum score was: 36.4 
The maximum score was 98.5 
The mean was 72.74 
The standard deviation was 13.19


Statistics for 2002
Exam 1
The minimum score was: 59.0 
The maximum score was 99.3 
The mean was 82.12 
The standard deviation was 9.8 
Exam 2
The minimum score was: 47.0 
The maximum score was 98.0 
The mean was 76.27 
The standard deviation was 13.77

## Question 2: 
Based on the required reading (and/or any other resources that you prefer), compare and contrast numpy arrays with python lists.

Write python code that contains a simple example which demonstrates one of the differences that you found. note: do not use the same example as the tutorial. Ensure that you cite any resources in a markdown cell.


In [119]:
print('Based on the module, python lists and numpy arrays have some advantages and disadvantages.\n'
      'The main difference that I found between these data structures is that python lists can contain\n'
      'any combination of datatypes while a numpy array is strict about only containing one datatype.\n'
      'Because of this, it is easier and quicker to perform operations on the elements of a numpy array.\n')

print('Some other differences are that numpy arrays can be multidimensional (1-D, 2-D, etc)\n'
      'while python can only be one-dimensional./n'
      'From the module, we also learned about the expansive numpy library,\n'
      'in comparison, lists do not utilize as many built-in functions.')

Based on the module, python lists and numpy arrays have some advantages and disadvantages.
The main difference that I found between these data structures is that python lists can contain
any combination of datatypes while a numpy array is strict about only containing one datatype.
Because of this, it is easier and quicker to perform operations on the elements of a numpy array.

Some other differences are that numpy arrays can be multidimensional (1-D, 2-D, etc)
while python can only be one-dimensional./nFrom the module, we also learned about the expansive numpy library,
in comparison, lists do not utilize as many built-in functions.


In [120]:
# create a list
list = [1, 2, 3, 4, 5]

try:
    # try decreasing each element in list by 1
    list = list - 1
    print(list)
except(TypeError):
    # return error if operation cannot be completed
    print('Python lists do not support this operation')
    
# create a numpy array with the same values
numpy_array = np.arange(1,6)

try:
    # try decreasing each element in list by 1
    numpy_array = numpy_array - 1
    print(numpy_array)
except(TypeError):
    # return error if operation cannot be completed
    print('Numpy arrays do not support this operation')
    
# as we can see, the list is not able to perform this operation while the numpy array is

Python lists do not support this operation
[0 1 2 3 4]


resources: https://www.geeksforgeeks.org/python-lists-vs-numpy-arrays/#

## Helpful resources 
Don't forget to cite websites which helped you solve a problem in a unique way.  You can do this in markdown near the code or with a simple one-line comment inside the code cell, or you can list them below. 

You do not need to cite the official python documentation.
